#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xl2tpd
Version  : 1.3.15
Release  : 1
URL      : https://github.com/xelerance/xl2tpd/archive/v1.3.15.tar.gz
Source0  : https://github.com/xelerance/xl2tpd/archive/v1.3.15.tar.gz
Source1  : xl2tpd.service
Summary  : Layer 2 Tunnelling Protocol Daemon (RFC 2661)
Group    : Development/Tools
License  : GPL-2.0
Requires: xl2tpd-bin = %{version}-%{release}
Requires: xl2tpd-license = %{version}-%{release}
Requires: xl2tpd-man = %{version}-%{release}
Requires: xl2tpd-services = %{version}-%{release}
BuildRequires : libpcap-dev
BuildRequires : util-linux

%description
xl2tpd is an implementation of the Layer 2 Tunnelling Protocol (RFC 2661).
L2TP allows you to tunnel PPP over UDP. Some ISPs use L2TP to tunnel user
sessions from dial-in servers (modem banks, ADSL DSLAMs) to back-end PPP
servers. Another important application is Virtual Private Networks where
the IPsec protocol is used to secure the L2TP connection (L2TP/IPsec,
RFC 3193). The L2TP/IPsec protocol is mainly used by Windows and
Mac OS X clients. On Linux, xl2tpd can be used in combination with IPsec
implementations such as Openswan.
Example configuration files for such a setup are included in this RPM.

xl2tpd works by opening a pseudo-tty for communicating with pppd.
It runs completely in userspace but supports kernel mode L2TP.

xl2tpd supports IPsec SA Reference tracking to enable overlapping internak
NAT'ed IP's by different clients (eg all clients connecting from their
linksys internal IP 192.168.1.101) as well as multiple clients behind
the same NAT router.

xl2tpd supports the pppol2tp kernel mode operations on 2.6.23 or higher,
or via a patch in contrib for 2.4.x kernels.

Xl2tpd is based on the 0.69 L2TP by Jeff McAdams <jeffm@iglou.com>
It was de-facto maintained by Jacco de Leeuw <jacco2@dds.nl> in 2002 and 2003.

%package bin
Summary: bin components for the xl2tpd package.
Group: Binaries
Requires: xl2tpd-license = %{version}-%{release}
Requires: xl2tpd-services = %{version}-%{release}

%description bin
bin components for the xl2tpd package.


%package license
Summary: license components for the xl2tpd package.
Group: Default

%description license
license components for the xl2tpd package.


%package man
Summary: man components for the xl2tpd package.
Group: Default

%description man
man components for the xl2tpd package.


%package services
Summary: services components for the xl2tpd package.
Group: Systemd services

%description services
services components for the xl2tpd package.


%prep
%setup -q -n xl2tpd-1.3.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571935298
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  PREFIX=/usr


%install
export SOURCE_DATE_EPOCH=1571935298
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xl2tpd
cp %{_builddir}/xl2tpd-1.3.15/LICENSE %{buildroot}/usr/share/package-licenses/xl2tpd/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/xl2tpd-1.3.15/debian/copyright %{buildroot}/usr/share/package-licenses/xl2tpd/f0e740a6bb96e38a721f7f59733e78a785f44446
%make_install PREFIX=/usr DESTDIR=%{buildroot}
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/xl2tpd.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pfc
/usr/bin/xl2tpd
/usr/bin/xl2tpd-control

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xl2tpd/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/xl2tpd/f0e740a6bb96e38a721f7f59733e78a785f44446

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pfc.1
/usr/share/man/man5/l2tp-secrets.5
/usr/share/man/man5/xl2tpd.conf.5
/usr/share/man/man8/xl2tpd-control.8
/usr/share/man/man8/xl2tpd.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/xl2tpd.service
